name: Sync Fork

on:
  schedule:
    - cron: '0 */3 * * *'  # Sync every 3 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Sync Fork Action
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh repo sync
